### DISCUSSION TITLE
Deploy Nuxt 3 with static files + server functions

### DISCUSSION THREAD

**Discussion by codeflorist** [jsmrcaga/action-netlify-deploy#64] [Q&A]
hi there!

many thanks for creating this action!

i'm trying to deploy a Nuxt application to Netlify, that has server-side routes as well as prerendered static content. it is built using "nuxt build" and the "netlify "Nitro-preset. this creates all static files inside the `.dist` folder. it also creates a `.netlify` folder structured like this:

```
- .netlify/
    - functions-internal/
        - nitro.json
        - server/
            - chunks/
                - _/
                - build/
                - routes/
                - virtual/
            - node_modules/
                - .....
            - main.mjs
            - main.mjs.map
            - server.mjs
            - package.json
```

here is my workflow-usage:

```
      - name: Deploy production to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.4.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: 'Deployed from GitHub action'
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: './dist'
          functions_directory: './.netlify'
          install_command: 'echo Skipping installing the dependencies'
          build_command: 'echo Skipping building the web files'
```

i've tried `./.netlify` as well as `./.netlify/functions-internal` and `./.netlify/functions-internal/server` for `functions_directory`, but the server-routes are not callable and throw a 404.

your script is outputting this in all 3 cases:
```
- Looking for a functions cache...
✔ No cached functions were found
```

do you have any idea how to deploy this Nuxt app with static files AND functions for server-side routes?
