### ISSUE TITLE
[bug]: Unexpected argument: deploy

### ISSUE THREAD

**Issue by imnotteixeira** [jsmrcaga/action-netlify-deploy#12]
Hey, before anything, congratulations on this package, it is really helpful!

My use case is deploying a folder to netlify. Before, I was using v1.1.0 and `NETLIFY_DEPLOY_TO_PROD = true`, but now I want to have deploy previews, which I assume would be done with `NETLIFY_DEPLOY_TO_PROD=false`. So I upgraded to v1.3.0 and added some params such as the deploy_alias, but I am getting an error like shown in the picture below.

![image](https://user-images.githubusercontent.com/28157246/106339414-6851c700-628e-11eb-8abc-4f410487e9ff.png)

This is my workflow, for reference. The step before deploying is building the resources, hence no build command needed.
```yml
name: Create Slate API Documentation (DEV)

on:
  pull_request:
    branches: 
      - develop
    paths:
      - "documentation/*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Build documentation
      uses: docker://decathlon/slate-builder-action:latest
      env:
        GITHUB_TOKEN: ${{ secrets.SLATE_TOKEN }}
        DOC_BASE_FOLDER: ./documentation
        ZIP_BUILD: false

    - name: Deploy Documentation
      uses: jsmrcaga/action-netlify-deploy@v1.3.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEV }}
        NETLIFY_DEPLOY_TO_PROD: false
        NETLIFY_DEPLOY_MESSAGE: ${{ github.sha }}
        deploy_alias: ${{ github.sha }}
        install_command: echo "No-op install"
        build_command: echo "No-op build"
        build_directory: documentation/build

``` 

Might this be some bug introduced in the latest version? I'd appreciate some help, thanks in advance!
