### ISSUE TITLE
Logging into your Netlify account

### ISSUE THREAD

**Issue by jrock2004** [jsmrcaga/action-netlify-deploy#17]
All of the sudden my builds are failing with `Logging into your Netlify account`. 

```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} 
          NETLIFY_SITE_ID: "my-id-to-netlify" 
          NETLIFY_DEPLOY_MESSAGE: "${{ github.event.head_commit.message }}"
          NETLIFY_DEPLOY_TO_PROD: ${{ github.event_name == 'push' && true || false }}
```

More logs

```
Error: Timed out waiting for authorization. If you do not have a Netlify 
 ›   account, please create one at https://app.netlify.com/signup, then run 
 ›   netlify login again.
```
