### ISSUE TITLE
deploy_alias is not a valid input and is not respected. 

### ISSUE THREAD

**Issue by mwolfhoffman** [jsmrcaga/action-netlify-deploy#18]
I am getting a warning that deploy_alias is not a valid input. 
My project then deploys to Netlify, but without the alias. 

Here is the warning text:

`Unexpected input(s) 'deploy_alias', valid inputs are ['entryPoint', 'args', 'NETLIFY_AUTH_TOKEN', 'NETLIFY_SITE_ID', 'NETLIFY_DEPLOY_TO_PROD', 'NETLIFY_DEPLOY_MESSAGE', 'build_directory', 'functions_directory']`

My yaml file:

```yaml
      
      - name: Print Branch Name
        run: echo ${BRANCH_NAME}

      - name: 'Deploy to Netlify'
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: Deploying ${{ env.BRANCH_NAME }} to Netlify
          build_directory: dist
          deploy_alias: ${{ env.BRANCH_NAME }}
```
