### ISSUE TITLE
Error: Timed out waiting for authorization

### ISSUE THREAD

**Issue by kfiven** [jsmrcaga/action-netlify-deploy#22]
When running this workflow against pull requests, it always fails.
Workflow:
```
name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy:
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1      
      - uses: jsmrcaga/action-netlify-deploy@master
        with:          
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE3_ID }}
          BUILD_DIRECTORY: "dist"
```

Error:
```
Logging into your Netlify account...
Opening https://app.netlify.com/authorize?response_type=ticket&ticket=50101582c52b703aa2554a7b61ac33
---------------------------
Error: Unable to open browser automatically: Running inside a docker container
Please open your browser and open the URL below:
https://app.netlify.com/authorize?response_type=ticket&ticket=50101582c52b703aa2554a7b61ac33
---------------------------
- Waiting for authorization...
 ›   Error: Timed out waiting for authorization. If you do not have a Netlify 
 ›   account, please create one at https://app.netlify.com/signup, then run 
 ›   netlify login again.
```
