### ISSUE TITLE
EACCES: permission denied during npm install

### ISSUE THREAD

**Issue by paurakhsharma** [jsmrcaga/action-netlify-deploy#34]
This happens once in a while. I haven't been able to reproduce it consistently.

This is now my workflow file looks like.

```
name: 'Deploy to Netlify'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.8.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: 'Prod deploy v${{ github.ref }}'
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: public
```

And my `npm run build` script does `npm install`

<details>
   <summary>
  This is the log I get in github actions.
  </summary>

```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated statsd-client@0.4.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
added 1404 packages, and audited 1405 packages in 1m
157 packages are looking for funding
  run `npm fund` for details
10 vulnerabilities (1 moderate, 9 high)
To address issues that do not require attention, run:
  npm audit fix
To address all issues possible (including breaking changes), run:
  npm audit fix --force
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
up to date, audited 1 package in 319ms
found 0 vulnerabilities
> nepali_christian_songs@1.0.0 build
> cd functions && npm install
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /github/home/.npm/_cacache/content-v2/sha1/1b/0a
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1001:[12](https://github.com/paurakhsharma/nepali_christian_songs/runs/6878223643?check_suite_focus=true#step:4:13)1 "/github/home/.npm"
npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2022-06-14T10_[13](https://github.com/paurakhsharma/nepali_christian_songs/runs/6878223643?check_suite_focus=true#step:4:14)_07_4[25](https://github.com/paurakhsharma/nepali_christian_songs/runs/6878223643?check_suite_focus=true#step:4:26)Z-debug-0.log
```

</details>
