### ISSUE TITLE
output is not accessible

### ISSUE THREAD

**Issue by raulfdm** [jsmrcaga/action-netlify-deploy#57]
Hi there 👋

I'm not sure if I'm doing something wrong but I'm not able to access the `output` values.

Here's my setup:

```yml
# ... setup ....

      - name: Netlify Deploy
        id: netlify_deploy
        uses: jsmrcaga/action-netlify-deploy@v2.1.0
        with:
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
          build_directory: ./apps/website/dist
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          deploy_alias: ${{ env.BRANCH_NAME }}
          NETLIFY_DEPLOY_TO_PROD: ${{ env.BRANCH_NAME == 'main' }}
          monorepo_package: website

      - name: Log
        shell: bash
        run: |
          echo ${{ steps.netlify_deploy.outputs.NETLIFY_LIVE_URL }}
          echo ${{ github.event_name}} # only to check if I'm able to echo something
```

The outcome of the "log" step is:

![CleanShot 2023-12-27 at 16 16 03@2x](https://github.com/jsmrcaga/action-netlify-deploy/assets/12464600/010023b7-8ebf-4fe6-a528-2c5ac6d5e915)

When I click to expand the first echo, I get:

```
echo 
  echo push
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NETLIFY_OUTPUT: Deploy path: /home/runner/work/taco-api/taco-api/apps/website/dist
  Deploying to draft URL...
  ​
  Netlify Build                                                 
  ────────────────────────────────────────────────────────────────
  ​
  ❯ Version
    @netlify/build 29.[3](https://github.com/raulfdm/taco-api/actions/runs/7341210874/job/19988519702?pr=65#step:7:3)1.0
  ​
  ❯ Flags
    auth: ***
    deployId: 658c771f317[4](https://github.com/raulfdm/taco-api/actions/runs/7341210874/job/19988519702?pr=65#step:7:4)[5](https://github.com/raulfdm/taco-api/actions/runs/7341210874/job/19988519702?pr=65#step:7:5)421f54ca0a7
    dir: ./apps/website/dist
    filter: website
    open: false
    prod: false
    prodIfUnlocked: false
    site: ***
    skipFunctionsCache: false
  ​
  ❯ Current directory
    /home/runner/work/taco-api/taco-api
  ​
  ❯ Config file
    No config file was defined: using default values.
  ​
  ❯ Context
    dev
  
  Build logs:        https://app.netlify.com/sites/taco-api/deploys/[6](https://github.com/raulfdm/taco-api/actions/runs/7341210874/job/19988519702?pr=65#step:7:6)58c[7](https://github.com/raulfdm/taco-api/actions/runs/7341210874/job/19988519702?pr=65#step:7:7)71f31745421f54ca0a7
  Function logs:     https://app.netlify.com/sites/taco-api/functions?scope=deploy:65[8](https://github.com/raulfdm/taco-api/actions/runs/7341210874/job/19988519702?pr=65#step:7:8)c771f3[17](https://github.com/raulfdm/taco-api/actions/runs/7341210874/job/19988519702?pr=65#step:7:17)454[21](https://github.com/raulfdm/taco-api/actions/runs/7341210874/job/19988519702?pr=65#step:7:21)f54ca0a7
  Website draft URL: https://658c771f[31](https://github.com/raulfdm/taco-api/actions/runs/7341210874/job/19988519702?pr=65#step:7:31)745421f54ca0a7--taco-api.netlify.app
  
  If everything looks good on your draft URL, deploy it to your main site URL with the --prod flag.
  netlify deploy --prod
    NETLIFY_PREVIEW_URL: https://658c771f31745421f54ca0a7--taco-api.netlify.app
    NETLIFY_LOGS_URL: https://app.netlify.com/sites/taco-api/deploys/658c771f31745421f54ca0a7
  https://app.netlify.com/sites/taco-api/functions?scope=deploy
    NETLIFY_LIVE_URL:
  ```
  
  which seems to be the output of Netlify CLI?
  
  Anyways, I'm not sure if it's a bug or if I'm doing something wrong. Please let me know
