### ISSUE TITLE
Cannot read properties of null (reading 'matches')

### ISSUE THREAD

**Issue by linonetwo** [jsmrcaga/action-netlify-deploy#63]
```
Run jsmrcaga/action-netlify-deploy@v2.2.0
  with:
    NETLIFY_AUTH_TOKEN: ***
    NETLIFY_DEPLOY_TO_PROD: true
    NETLIFY_SITE_ID: 97bd95f9-xxx
    build_directory: ./dist
    NETLIFY_DEPLOY_MESSAGE: Deployed from GitHub action
    netlify_path: netlify
    build_command: npm run build
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    STORE_PATH: /home/runner/setup-pnpm/node_modules/.bin/store/v3
Run /home/runner/work/_actions/jsmrcaga/action-netlify-deploy/v2.2.0/entrypoint.sh
npm error Cannot read properties of null (reading 'matches')
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-01-31T17_13_11_357Z-debug-0.log
```
