### ISSUE TITLE
Missing script: build

### ISSUE THREAD

**Issue by builtbybrayne** [jsmrcaga/action-netlify-deploy#9]
Hi,

I'm getting the following error(s) trying to deploy:

```
Run jsmrcaga/action-netlify-deploy@v1.2.0
/usr/bin/docker run --name b51f0f79fd8b651461da05fdef39a2bdef9_9c6b9e --label 654b51 --workdir /github/workspace --rm -e INPUT_NETLIFY_AUTH_TOKEN -e INPUT_NETLIFY_SITE_ID -e INPUT_NETLIFY_DEPLOY_TO_PROD -e INPUT_BUILD_DIRECTORY -e INPUT_NETLIFY_DEPLOY_MESSAGE -e INPUT_FUNCTIONS_DIRECTORY -e INPUT_INSTALL_COMMAND -e INPUT_BUILD_COMMAND -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/docs/docs":"/github/workspace" 654b51:f0f79fd8b651461da05fdef39a2bdef9  "***" "***" "true" "public" "" "npm i" "npm run build"
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys

added 1362 packages, and audited 1362 packages in 2m

91 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (1 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

up to date in 179ms

found 0 vulnerabilities
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2020-11-06T12_52_05_722Z-debug.log
 ›   Error: Unauthorized
```

I can see two potential contenders:
1) Missing script: build
2) Error: Unauthorized

I'm inclined to think that the second might be due to the first, and am as sure as I can be that I've used the right token and site id. But I'm thrown by the `missing script: build` reference.

The setup is:

```
- name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.2.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: public     
```

Any ideas?

Thanks in advance
